In [4]:
import tensorflow as tf
import warnings 
warnings.filterwarnings('ignore')
print(f"Tensorflow version: {tf.__version__}")

Tensorflow version: 2.16.2


In [2]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [18]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2), # when used only the 8 percent is used
  tf.keras.layers.Dense(10),
])
model.summary()
# can use more than one layers ie   tf.keras.layers.Dense(128, activation='relu'),
# tf.keras.layers.Dropout(0.2),
  # tf.keras.layers.Flatten(input_shape=(28, 28)),
  # tf.keras.layers.Dense(128, activation='relu'),
  # tf.keras.layers.Dropout(0.2), # when used only the 8 percent is used
  # tf.keras.layers.Dense(64, activation='relu')
  # tf.keras.layers.Dropout(0.2)
  # tf.keras.layers.Dense(10, activation='softmax'),


Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten_5 (Flatten)             │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 128)            │       100,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 101,770 (397.54 KB)

 Trainable params: 101,770 (397.54 KB)

 Non-trainable params: 0 (0.00 B)

In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.00651011, -0.47518593,  0.01110034,  0.53980345,  0.16388243,
        -1.041869  ,  0.42911467, -0.50194263, -0.6204844 ,  0.19916488]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.10166603, 0.0636257 , 0.10347228, 0.17556456, 0.12055256,
        0.0361015 , 0.15716843, 0.06194586, 0.05502122, 0.12488186]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

3.321421

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.8592 - loss: 0.4814
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9561 - loss: 0.1484
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9679 - loss: 0.1082
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9720 - loss: 0.0892
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9779 - loss: 0.0718


In [12]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 2s - 5ms/step - accuracy: 0.9747 - loss: 0.0826


[0.08257584273815155, 0.9746999740600586]

In [13]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [14]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.2354326e-09, 2.1377785e-08, 5.7335467e-07, 6.1122759e-04,
        2.5899815e-11, 1.4131297e-06, 1.2470007e-15, 9.9938595e-01,
        4.7158164e-08, 8.3450936e-07],
       [2.1699373e-08, 5.8519681e-06, 9.9970466e-01, 2.8278577e-04,
        5.7934088e-13, 5.0861991e-06, 1.6051805e-06, 1.3464728e-13,
        2.3055815e-08, 2.2737881e-12],
       [8.8161647e-07, 9.9940181e-01, 1.7414357e-04, 1.9622883e-05,
        1.2850838e-05, 8.0240297e-06, 7.7758246e-05, 1.4511216e-04,
        1.5453681e-04, 5.2635769e-06],
       [9.9982125e-01, 4.5084807e-09, 1.0492549e-05, 3.0770793e-06,
        6.4162887e-05, 8.6158698e-06, 4.6114768e-05, 2.0833917e-05,
        4.2663888e-08, 2.5423969e-05],
       [6.7409587e-06, 3.9048717e-07, 1.6828282e-05, 7.4005260e-07,
        9.9751413e-01, 5.7852213e-07, 3.4269407e-05, 2.4691768e-04,
        2.3466912e-06, 2.1769379e-03]], dtype=float32)>