# JOMO KENYATTA UNIVERSITY OF AGRICULTURE AND TECHNOLOGY
- BACHELOR OF SCIENCE IN INFORMATION TECHNOLOGY 
- BIT 2319 ARTIFICIAL INTELLIGENCE
- LAB PRACTICAL V: PYTHON BASICS

1.	Check the version of pandas and numpy installed using the following commands:
import numpy; print (numpy.version.version) #numpy version
import pandas as pd; print (pd.__version__)  #pandas version
2.	Write a program to print 'Hello BBC/BIT Year 3 AI Team’. Repeat the output 10 times
3.	Write a program to define two variables, calculate their sum and display the results
4.	Write a program to define a tuple that contains only one element.
b) Write a program to define a tuple and then use the 'for loop' to print all the elements.
6.	Write code to create a Python dictionary (the dict type) and print out the details. Add two entries to the dictionary: Associate the key ‘name’ with the value ‘Reagan’, and associate the key ‘phone’ with ‘+254 722 222333’
7.	Define the variable s as the string s=“Almost Done with AI"
a.	What is the value of 3*x?   b)  What is the value of x[1]?
b.	What is the value of x[-1]?  d) What is the value of x[::2]?
8.	Use the following declarations to answer the questions below:
import string
text = “BIT/BBC AI Comrades "
a.	print ("upper", "=>", string.upper(text))
b.	print ("lower", "=>", string.lower(text))
c.	print ("split", "=>", string.split(text))
d.	print ("join", "=>", string.join(string.split(text), "+"))
e.	print ("replace", "=>", string.replace(text, "Python", "Java"))
f.	print ("find", "=>", string.find(text, "Python"), string.find(text, "Java"))
g.	print ("count", "=>", string.count(text, "n"))
9.	Define the variable s as the string s = “Almost Done with AI"
10.	Use a for/while loop to:
a.	Print the numbers 0 to 100 
b.	Print the numbers 0 to 100 that are divisible by 7
c.	Print the numbers 1 to 100 that are divisible by 5 but not by 3
d.	Print for each of the numbers x = 2; : : : 20, all numbers that divide x, excluding 1 and x. Hence, for 18, it should print 2 3 6 9.
11.	
a.	Define a function to do Multiplication, such as Mul(8,6),and it output 42.
b.	Complete the function definition so it returns the square of the product of the parameters, so sqrProd(2, 5) returns (2*5)*(2*5) = 100.
def sqrProd(x, y):
12.	Import numpy and then:
a.	Use numpy to define an array, the shape of it is (5,5) and all elements of it is 0.
b.	Create a 3x3 matrix with values ranging from 0 to 8
c.	Find indices of non-zero elements from [1,2,0,0,4,0]
d.	Create a 10x10 array with random values and find the minimum and maximum values
e.	Create a random vector of size 30 and find the mean value 
13.	Write a Python program that prompts the user for two numbers, reads them in, and prints out the product, sum, difference and quotient using an appropriate format and labeled appropriately.
14.	
a.	Complete the code for the following function so it matches its documentation:
def doubleList(numberList):
For each of the numbers in the list numberList, print a line containing twice the original number. For example,
doubleList ([3, 1, 5]) would print 6, 2, 10
b.	Write a function that evaluates the polynomial 3x2 - x + 2.  Test with x = 3 and share your results
c.	Write a function my_max(x,y) that returns the maximum of x and y. Do not use the max function, but use it instead in following two ways:
i.	Use both if and else.
ii.	Use if but not else (nor elif).
d.	Write a program to read and calculate the area and circumference of a circle using two functions, area() and circum().
15.	Object Oriented Programming
a. Create a Vehicle class with max_speed and mileage instance attributes. Create an instance of the Vehicle class and use the following data with appropriate methods to read and display the values (max_speed: 240 km/hr, mileage: 10,000 km)
b.	Create child class Bus that will inherit all of the variables and methods of the Vehicle class, and has name attribute. Use the following data to test your class; Name: "School Mercedes", max_speed = 180, mileage = 1000. Test and display members of Bus class
c.	Create a Bus class that inherits from the Vehicle class. Add an attribute the seating_capacity and give the argument of Bus.seating_capacity() a default value of 50.
d.	Define a class attribute”color” with a default value white. i.e., Every Vehicle should be white. Test and display members of both the Vehicle and Bus classes.




In [1]:
# Question 1 checking the version of pandas and numpy
import pandas as pd
import numpy as np
# numpy version
print(np.version.version)
# pandas version
print(pd.__version__)

1.26.4
2.2.2


In [91]:
# question 2 Write a program to print 'Hello BBC/BIT Year 3 AI Team’. Repeat the output 10 times
text = 'Hello BBC/BIT Year 3 AI Team'
i = 1
while i<=10:
    print(text)
    i += 1

Hello BBC/BIT Year 3 AI Team
Hello BBC/BIT Year 3 AI Team
Hello BBC/BIT Year 3 AI Team
Hello BBC/BIT Year 3 AI Team
Hello BBC/BIT Year 3 AI Team
Hello BBC/BIT Year 3 AI Team
Hello BBC/BIT Year 3 AI Team
Hello BBC/BIT Year 3 AI Team
Hello BBC/BIT Year 3 AI Team
Hello BBC/BIT Year 3 AI Team


In [4]:
# Question 3.Write a program to define two variables, calculate their sum and display the results
num1 = int(input('Enter Value 1: '))
num2 = int(input('Enter Value 2: '))
summation = num1 + num2
print(f"The sum is: {summation}")

Enter Value 1:  4
Enter Value 2:  5


The sum is: 9


In [8]:
# Question 4. Write a program to define a tuple that contains only one element.
number = (1,)
type(number
    
# question 4. b) Write a program to define a tuple and then use the 'for loop' to print all the elements.
numbers = (1,2,3,4,5,6,7,8,9)
for values in numbers:
    print(values)
    

1
2
3
4
5
6
7
8
9


In [41]:
# Question 5) Write code to create a Python dictionary (the dict type) and print out the details. 
# Add two entries to the dictionary: Associate the key ‘name’ with the value ‘Reagan’, 
# and associate the key ‘phone’ with ‘+254 722 222333’
studentDetails = {"Names":["James", "Paul", "Peter", "Joe"],
                  "Phone":['+254714678290', '+254792017389', '+254751672917', '+254753001278']}
# adding 2 entries
studentDetails['Names'].append('Reagan')
studentDetails['Phone'].append('+254 722 222333')
# print all the values on the dictionary

for key in studentDetails:
    print(studentDetails[key])

In [19]:
# Question 6) Define the variable s as the string s=“Almost Done with AI" 
# a. What is the value of 3*x? 
# b) What is the value of x[1]? b. What is the value of x[-1]? d) What is the value of x[::2]?
x = "Almost Done With AI"

# print value of 3 * x
print(3*x)

# what is the value of x[1]
print(f"value of s[1]->{x[1]}")

# value of s[-1]
print(f"value of s[-1]-> {x[-1]}")

# value of s[::2]
print(f"value of s[::2]-> {x[::2]}")

Almost Done With AIAlmost Done With AIAlmost Done With AI
value of s[1]->l
value of s[-1]-> I
value of s[::2]-> Ams oeWt I


In [24]:
# Question 7) Use the following declarations to answer the questions below: import string text = “BIT/BBC AI Comrades " 
# a. print ("upper", "=>", string.upper(text)) 
# b. print ("lower", "=>", string.lower(text)) 
# c. print ("split", "=>", string.split(text)) 
# d. print ("join", "=>", string.join(string.split(text), "+")) 
# e. print ("replace", "=>", string.replace(text, "Python", "Java")) 
# f. print ("find", "=>", string.find(text, "Python"), string.find(text, "Java")) 
# g. print ("count", "=>", string.count(text, "n"))

import string
text = "BIT/BBC AI Comrades"

# a) print ("upper", "=>", string.upper(text))
print(f"Upper => {text.upper()}")

# b. print ("lower", "=>", string.lower(text)) 
print (f"Lower => {text.lower()}")

# c. print ("split", "=>", string.split(text))
print(f"Split => {text.split()}")

# d. print ("join", "=>", string.join(string.split(text), "+")) 
split = text.split()
print(f"Join", "=>",  "+".join(split))

# e. print ("replace", "=>", string.replace(text, "Python", "Java")) 
value = "Python ia a cool Language"
print(f"Replace => {value.replace("Python", "Java")}")


# f. print ("find", "=>", string.find(text, "Python"), string.find(text, "Java")) 
print(f"Find Python => {value.find("Python")}")
print(f"Find Java => {value.find("Java")}")

# g. print ("count", "=>", string.count(text, "n"))
print("Count", "=>", value.count("n"))

Upper => BIT/BBC AI COMRADES
Lower => bit/bbc ai comrades
Split => ['BIT/BBC', 'AI', 'Comrades']
Join => BIT/BBC+AI+Comrades
Replace => Java ia a cool Language
Find Python => 0
Find Java =>-1
Count => 2


In [79]:
# question 8) Define the variable s as the string s = “Almost Done with AI"
s = "Almost Done With AI"
print(s)

Almost Done With AI


In [8]:
# Question 9) Use a for/while loop to: a. Print the numbers 0 to 100 
# b. Print the numbers 0 to 100 that are divisible by 7 
# c. Print the numbers 1 to 100 that are divisible by 5 but not by 3 
# d. Print for each of the numbers x = 2; : : : 20, all numbers that divide x, excluding 1 and x. Hence, for 18, it should print 2 3 6 9.

# for loop print numbers 0 to 100
# for i in range(0, 101):
#     print(i)

# # # while loop
# i = 0
# while i <= 100:
#     print(i)
#     i+=1

# # # =======================================================================================================

# # b. Print the numbers 0 to 100 that are divisible by 7 using for loop
# for num in range(0,101):
#     if num % 7 == 0:
#         print(num)

# # b. Print the numbers 0 to 100 that are divisible by 7 using while loop
# num = 0
# while num <= 100:
#     if num % 7 == 0:
#         print(num)
#     num+=1 # increment num to prevent infinity loops
    
# # =======================================================================================================

# # c. Print the numbers 1 to 100 that are divisible by 5 but not by 3 
# for value in range(0, 101):
#     if value % 5 == 0 and value % 3 != 0:
#         print(value)

# # # while loop
# value = 0
# while value <= 100:
#     if value % 5 == 0 and value % 3 != 0:
#         print(value)
#     value += 1

# # ======================================================================================================

# d. Print for each of the numbers x = 2; : : : 20, all numbers that divide x, excluding 1 and x. Hence, for 18, it should print 2 3 6 9.
            # 18 % 2 == 0 → Prints 2
            # 18 % 3 == 0 → Prints 3
            # 18 % 6 == 0 → Prints 6
            # 18 % 9 == 0 → Prints 9
# for num in range(2, 21):
#     print(f"Divisiors of {num} (excluding 1 and {num}):", end=" ")
#     found = False # boolean variable
#     for i in range(2, num):
#         if num % i == 0:
#             print(i, end=" ")
#             found=True
#     if not found:
#         print('None', end=" ")
#     print()

# =======================================================================================================

0
7
14
21
28
35
42
49
56
63
70
77
84
91
98


In [5]:
# Question 10) a. Define a function to do Multiplication, such as Mul(8,6),and it output 42. 
# b. Complete the function definition so it returns the square of the product of the parameters,
# so sqrProd(2, 5) returns (25)(2*5) = 100. def sqrProd(x, y)

# a) Function to do Multiplication
def mul(a,b):
    """Function that takes some parameters and 
    returns a multiplication of those parameters"""
    return a*b
mul(8,6)

# function definition
def sqrProd(x, y):
    """A Function that takes some parameters, 
    declares a varible output that performs multiplication on two numbers
    then returns a square of the output variable"""
    output = x*y
    return output**2
sqrProd(2, 5)

100

In [39]:
# Question 11) Import numpy and then: 
# a. Use numpy to define an array, the shape of it is (5,5) and all elements of it is 0. 
# b. Create a 3x3 matrix with values ranging from 0 to 8 
# c. Find indices of non-zero elements from [1,2,0,0,4,0] 
# d. Create a 10x10 array with random values and find the minimum and maximum values 
# e. Create a random vector of size 30 and find the mean value

# use numpy to define an array, the shape of it is (5,5) and all elements of it is 0
import numpy as np
zero = np.zeros((5,5))
zero

# create a 3*3 matrix with values ranging from 0 to 8
matrix = np.arange(0,9).reshape(3,3)
matrix

# Find indices of non-zero elements from [1, 2, 0, 0, 4, 0]
elements = np.array([1, 2, 0, 0, 4, 0])
elements[np.nonzero(elements)]

# Create a 10 * 10 array with random values and find the minimum and maximum values
random = np.random.randint(10, size=(10,10))
minimum = np.min(random)
maximum = np.max(random)
print("Random Array->", random)
print("Maximum value->", maximum)
print("Minimum value->", minimum)

# random Vector of size 30 and find the mean value
vector = np.random.rand(30)
meanValue = np.mean(vector)
print(f"Mean Vector-> {meanValue}")

Random Array-> [[4 2 1 3 3 3 0 3 8 9]
 [0 5 3 3 7 0 1 2 6 6]
 [8 0 1 8 1 4 4 6 6 9]
 [6 3 9 1 5 8 0 8 5 5]
 [7 1 6 0 3 0 8 6 2 4]
 [3 1 4 3 2 0 3 8 2 3]
 [0 7 7 9 8 7 2 2 6 1]
 [0 2 6 7 1 8 5 5 6 3]
 [2 6 3 3 7 3 4 5 1 3]
 [6 1 5 8 6 1 3 0 1 3]]
Maximum value-> 9
Minimum value-> 0
Mean Vector-> 0.4267097978542572


In [ ]:
# Question 12 Write a Python program that prompts the user for two numbers, 
# reads them in, and prints out the product, sum, difference and quotient using an appropriate format and labeled appropriately.
import math
num1 = int(input("Enter Number 1: "))
num2 = int(input("Enter Number 2: "))
product = num1 * num2
Total = num1 + num2
Difference = num1 - num2
Quotient = num1//num2
print(f"The Product of {num1}*{num2} is -> {product}")
print(f"The Total of {num1}+{num2} is -> {Total}")
print(f"The Difference of {num1}-{num2} is -> {Difference}")
print(f"The Quotient of {num1}//{num2} is -> {Quotient}")

<h4>Question 13</h4>

1) Complete the code for the following function so it matches its documentation: def doubleList(numberList): For each of the numbers in the list numberList, print a line containing twice the original number. For example, doubleList ([3, 1, 5]) would print 6, 2, 10 
2) Write a function that evaluates the polynomial 3x2 - x + 2. Test with x = 3 and share your results
3) Write a function my_max(x,y) that returns the maximum of x and y. Do not use the max function, but use it instead in following two ways: i. Use both if and else. ii. Use if but not else (nor elif).
4) Write a program to read and calculate the area and circumference of a circle using two functions, area() and circum().

Signature: mul(a, b)
Source:   
def mul(a,b):
    """Function that takes some parameters and 
    returns a multiplication of those parameters"""
    return a*b
File:      /var/folders/6w/_1xx55992tqfg37yz_8bt5v80000gn/T/ipykernel_43359/3232276529.py
Type:      function

125