In [2]:
import pandas as pd

In [3]:
s = pd.Series([1,2,3],
             index=['A', 'B', 'C'],
             name='col1')

In [4]:
data = [[1,4], [2,5], [3,6]]
index = ['A', 'B', 'C']
df1 = pd.DataFrame(data, index=index, columns=['col1', 'col2'])

In [32]:
df = pd.read_csv("/Users/briankimanzi/Downloads/lung_disease_data.csv", encoding='utf-8')
df

Age  Gender Smoking Status  Lung Capacity Disease Type Treatment Type  \
0     71.0  Female             No           4.49         COPD        Therapy   
1     34.0  Female            Yes            NaN   Bronchitis        Surgery   
2     80.0    Male            Yes           1.95         COPD            NaN   
3     40.0  Female            Yes            NaN   Bronchitis     Medication   
4     43.0    Male            Yes           4.60         COPD        Surgery   
...    ...     ...            ...            ...          ...            ...   
5195  40.0    Male             No           1.43  Lung Cancer     Medication   
5196  21.0     NaN            Yes           1.50         COPD     Medication   
5197  42.0  Female             No           5.53    Pneumonia        Surgery   
5198  82.0    Male             No           3.68   Bronchitis     Medication   
5199  45.0  Female            Yes           3.79    Pneumonia     Medication   

      Hospital Visits Recovered  
0                14.0       Yes  
1                 7.0        No  
2                 4.0       Yes  
3                 1.0        No  
4                 NaN       Yes  
...               ...       ...  
5195              1.0       Yes  
5196              4.0        No  
5197              5.0        No  
5198              9.0        No  
5199             10.0       Yes  

[5200 rows x 8 columns]

In [6]:
pd.reset_option('display.Max_rows', None)

In [23]:
df[['Gender', 'Smoking Status', 'Lung Capacity']]

Gender Smoking Status  Lung Capacity
0     Female             No           4.49
1     Female            Yes            NaN
2       Male            Yes           1.95
3     Female            Yes            NaN
4       Male            Yes           4.60
...      ...            ...            ...
5195    Male             No           1.43
5196     NaN            Yes           1.50
5197  Female             No           5.53
5198    Male             No           3.68
5199  Female            Yes           3.79

[5200 rows x 3 columns]

In [144]:
df.iloc[:,[2, 3, 4]] # [index:column]

Smoking Status  Lung Capacity Disease Type
0                No           4.49         COPD
1               Yes            NaN   Bronchitis
2               Yes           1.95         COPD
3               Yes            NaN   Bronchitis
4               Yes           4.60         COPD
...             ...            ...          ...
5195             No           1.43  Lung Cancer
5196            Yes           1.50         COPD
5197             No           5.53    Pneumonia
5198             No           3.68   Bronchitis
5199            Yes           3.79    Pneumonia

[5200 rows x 3 columns]

In [32]:
df.head(20)

Age  Gender Smoking Status  Lung Capacity Disease Type Treatment Type  \
0   71.0  Female             No           4.49         COPD        Therapy   
1   34.0  Female            Yes            NaN   Bronchitis        Surgery   
2   80.0    Male            Yes           1.95         COPD            NaN   
3   40.0  Female            Yes            NaN   Bronchitis     Medication   
4   43.0    Male            Yes           4.60         COPD        Surgery   
5   22.0  Female             No           3.65   Bronchitis     Medication   
6   41.0    Male            Yes           2.98       Asthma     Medication   
7   72.0    Male            NaN           2.61  Lung Cancer        Surgery   
8   21.0  Female             No           4.05  Lung Cancer     Medication   
9   49.0    Male            Yes           5.70    Pneumonia     Medication   
10  57.0  Female            Yes           4.36   Bronchitis        Therapy   
11  21.0    Male             No           1.37    Pneumonia        Surgery   
12  83.0    Male             No           3.30    Pneumonia        Therapy   
13  79.0    Male            Yes           5.45   Bronchitis     Medication   
14  40.0  Female             No           1.47  Lung Cancer     Medication   
15   NaN  Female             No           5.94   Bronchitis        Therapy   
16  77.0    Male            Yes           5.75       Asthma        Therapy   
17  41.0  Female            NaN           1.39    Pneumonia        Therapy   
18  68.0     NaN            Yes           5.67    Pneumonia     Medication   
19  78.0  Female            Yes           2.82          NaN            NaN   

    Hospital Visits Recovered  
0              14.0       Yes  
1               7.0        No  
2               4.0       Yes  
3               1.0        No  
4               NaN       Yes  
5              11.0       Yes  
6              12.0       Yes  
7              11.0       Yes  
8              12.0        No  
9              11.0       Yes  
10             11.0       Yes  
11              1.0       Yes  
12              8.0       Yes  
13             12.0        No  
14             13.0       Yes  
15              9.0        No  
16             11.0        No  
17              3.0       Yes  
18              7.0       Yes  
19             13.0       Yes

# Data Wrangling

In [60]:
df

Age  Gender Smoking Status  Lung Capacity Disease Type Treatment Type  \
0     71.0  Female             No           4.49         COPD        Therapy   
1     34.0  Female            Yes            NaN   Bronchitis        Surgery   
2     80.0    Male            Yes           1.95         COPD            NaN   
3     40.0  Female            Yes            NaN   Bronchitis     Medication   
4     43.0    Male            Yes           4.60         COPD        Surgery   
...    ...     ...            ...            ...          ...            ...   
5195  40.0    Male             No           1.43  Lung Cancer     Medication   
5196  21.0     NaN            Yes           1.50         COPD     Medication   
5197  42.0  Female             No           5.53    Pneumonia        Surgery   
5198  82.0    Male             No           3.68   Bronchitis     Medication   
5199  45.0  Female            Yes           3.79    Pneumonia     Medication   

      Hospital Visits Recovered  
0                14.0       Yes  
1                 7.0        No  
2                 4.0       Yes  
3                 1.0        No  
4                 NaN       Yes  
...               ...       ...  
5195              1.0       Yes  
5196              4.0        No  
5197              5.0        No  
5198              9.0        No  
5199             10.0       Yes  

[5200 rows x 8 columns]

In [59]:
df.sort_values(['Age', 'Lung Capacity'],
              ascending=[False, True]) # sorting values in ascending order

Age  Gender Smoking Status  Lung Capacity Disease Type Treatment Type  \
4784  89.0    Male             No           1.02    Pneumonia     Medication   
1473  89.0  Female             No           1.19  Lung Cancer     Medication   
3768  89.0  Female             No           1.32         COPD     Medication   
2203  89.0  Female             No           1.38  Lung Cancer     Medication   
2775  89.0  Female             No           1.41  Lung Cancer        Therapy   
...    ...     ...            ...            ...          ...            ...   
2143   NaN  Female             No            NaN         COPD        Surgery   
2519   NaN  Female            Yes            NaN         COPD     Medication   
2942   NaN    Male            Yes            NaN         COPD     Medication   
3514   NaN  Female            Yes            NaN       Asthma        Therapy   
4660   NaN  Female             No            NaN    Pneumonia     Medication   

      Hospital Visits Recovered  
4784              3.0        No  
1473              6.0       NaN  
3768              NaN       Yes  
2203              8.0        No  
2775             12.0       Yes  
...               ...       ...  
2143              8.0       Yes  
2519             11.0        No  
2942             14.0       Yes  
3514             10.0        No  
4660              3.0       Yes  

[5200 rows x 8 columns]

In [66]:
df.loc[df.duplicated()] # locates all duplicated values

Age  Gender Smoking Status  Lung Capacity Disease Type Treatment Type  \
5000  83.0  Female             No           3.55         COPD     Medication   
5005  23.0    Male             No           5.96  Lung Cancer     Medication   
5006  66.0    Male            Yes           5.24    Pneumonia        Surgery   
5007  35.0    Male            Yes           4.69   Bronchitis        Therapy   
5009  31.0    Male             No           5.51    Pneumonia        Therapy   
...    ...     ...            ...            ...          ...            ...   
5192  31.0  Female             No           1.51    Pneumonia        Surgery   
5195  40.0    Male             No           1.43  Lung Cancer     Medication   
5197  42.0  Female             No           5.53    Pneumonia        Surgery   
5198  82.0    Male             No           3.68   Bronchitis     Medication   
5199  45.0  Female            Yes           3.79    Pneumonia     Medication   

      Hospital Visits Recovered  
5000              6.0        No  
5005              1.0       Yes  
5006             14.0        No  
5007              6.0        No  
5009              3.0       Yes  
...               ...       ...  
5192              6.0       Yes  
5195              1.0       Yes  
5197              5.0        No  
5198              9.0        No  
5199             10.0       Yes  

[91 rows x 8 columns]

In [76]:
df = df.transpose()
df = df.T

In [81]:
df['person']= df['Age']

In [87]:
df.drop(index= [0, 1, 2])

Age  Gender Smoking Status  Lung Capacity Disease Type Treatment Type  \
3     40.0  Female            Yes            NaN   Bronchitis     Medication   
4     43.0    Male            Yes           4.60         COPD        Surgery   
5     22.0  Female             No           3.65   Bronchitis     Medication   
6     41.0    Male            Yes           2.98       Asthma     Medication   
7     72.0    Male            NaN           2.61  Lung Cancer        Surgery   
...    ...     ...            ...            ...          ...            ...   
5195  40.0    Male             No           1.43  Lung Cancer     Medication   
5196  21.0     NaN            Yes           1.50         COPD     Medication   
5197  42.0  Female             No           5.53    Pneumonia        Surgery   
5198  82.0    Male             No           3.68   Bronchitis     Medication   
5199  45.0  Female            Yes           3.79    Pneumonia     Medication   

      Hospital Visits Recovered  
3                 1.0        No  
4                 NaN       Yes  
5                11.0       Yes  
6                12.0       Yes  
7                11.0       Yes  
...               ...       ...  
5195              1.0       Yes  
5196              4.0        No  
5197              5.0        No  
5198              9.0        No  
5199             10.0       Yes  

[5197 rows x 8 columns]

In [33]:
clone = df.copy()

In [90]:
clone

Age  Gender Smoking Status  Lung Capacity Disease Type Treatment Type  \
0     71.0  Female             No           4.49         COPD        Therapy   
1     34.0  Female            Yes            NaN   Bronchitis        Surgery   
2     80.0    Male            Yes           1.95         COPD            NaN   
3     40.0  Female            Yes            NaN   Bronchitis     Medication   
4     43.0    Male            Yes           4.60         COPD        Surgery   
...    ...     ...            ...            ...          ...            ...   
5195  40.0    Male             No           1.43  Lung Cancer     Medication   
5196  21.0     NaN            Yes           1.50         COPD     Medication   
5197  42.0  Female             No           5.53    Pneumonia        Surgery   
5198  82.0    Male             No           3.68   Bronchitis     Medication   
5199  45.0  Female            Yes           3.79    Pneumonia     Medication   

      Hospital Visits Recovered  
0                14.0       Yes  
1                 7.0        No  
2                 4.0       Yes  
3                 1.0        No  
4                 NaN       Yes  
...               ...       ...  
5195              1.0       Yes  
5196              4.0        No  
5197              5.0        No  
5198              9.0        No  
5199             10.0       Yes  

[5200 rows x 8 columns]

In [96]:
df2 = clone[['Age', 'Lung Capacity']] + 5
pd.concat([df2, clone])

Age  Lung Capacity  Gender Smoking Status Disease Type Treatment Type  \
0     76.0           9.49     NaN            NaN          NaN            NaN   
1     39.0            NaN     NaN            NaN          NaN            NaN   
2     85.0           6.95     NaN            NaN          NaN            NaN   
3     45.0            NaN     NaN            NaN          NaN            NaN   
4     48.0           9.60     NaN            NaN          NaN            NaN   
...    ...            ...     ...            ...          ...            ...   
5195  40.0           1.43    Male             No  Lung Cancer     Medication   
5196  21.0           1.50     NaN            Yes         COPD     Medication   
5197  42.0           5.53  Female             No    Pneumonia        Surgery   
5198  82.0           3.68    Male             No   Bronchitis     Medication   
5199  45.0           3.79  Female            Yes    Pneumonia     Medication   

      Hospital Visits Recovered  
0                 NaN       NaN  
1                 NaN       NaN  
2                 NaN       NaN  
3                 NaN       NaN  
4                 NaN       NaN  
...               ...       ...  
5195              1.0       Yes  
5196              4.0        No  
5197              5.0        No  
5198              9.0        No  
5199             10.0       Yes  

[10400 rows x 8 columns]

In [113]:
df3 = pd.DataFrame([[7], [8], [9]], 
                  index=['A', 'B', 'C'],
                  columns=['cols3'])

In [119]:
df1

col1  col2
A     1     4
B     2     5
C     3     6

In [125]:
df1.merge(df3, right_index=True, left_index=True) # inner Join

col1  col2  cols3
A     1     4      7
B     2     5      8
C     3     6      9

In [133]:
df.isna().sum() # checks all columns in the dataframe with null values

Age                300
Gender             300
Smoking Status     300
Lung Capacity      300
Disease Type       300
Treatment Type     300
Hospital Visits    300
Recovered          300
dtype: int64

In [141]:
df.fillna(df.bfill())

Age  Gender Smoking Status  Lung Capacity Disease Type Treatment Type  \
0     71.0  Female             No           4.49         COPD        Therapy   
1     34.0  Female            Yes           1.95   Bronchitis        Surgery   
2     80.0    Male            Yes           1.95         COPD     Medication   
3     40.0  Female            Yes           4.60   Bronchitis     Medication   
4     43.0    Male            Yes           4.60         COPD        Surgery   
...    ...     ...            ...            ...          ...            ...   
5195  40.0    Male             No           1.43  Lung Cancer     Medication   
5196  21.0  Female            Yes           1.50         COPD     Medication   
5197  42.0  Female             No           5.53    Pneumonia        Surgery   
5198  82.0    Male             No           3.68   Bronchitis     Medication   
5199  45.0  Female            Yes           3.79    Pneumonia     Medication   

      Hospital Visits Recovered  
0                14.0       Yes  
1                 7.0        No  
2                 4.0       Yes  
3                 1.0        No  
4                11.0       Yes  
...               ...       ...  
5195              1.0       Yes  
5196              4.0        No  
5197              5.0        No  
5198              9.0        No  
5199             10.0       Yes  

[5200 rows x 8 columns]

In [157]:
clone

Age  Gender Smoking Status  Lung Capacity Disease Type Treatment Type  \
0     71.0  Female             No           4.49         COPD        Therapy   
1     34.0  Female            Yes            NaN   Bronchitis        Surgery   
2     80.0    Male            Yes           1.95         COPD            NaN   
3     40.0  Female            Yes            NaN   Bronchitis     Medication   
4     43.0    Male            Yes           4.60         COPD        Surgery   
...    ...     ...            ...            ...          ...            ...   
5195  40.0    Male             No           1.43  Lung Cancer     Medication   
5196  21.0     NaN            Yes           1.50         COPD     Medication   
5197  42.0  Female             No           5.53    Pneumonia        Surgery   
5198  82.0    Male             No           3.68   Bronchitis     Medication   
5199  45.0  Female            Yes           3.79    Pneumonia     Medication   

      Hospital Visits Recovered  
0                14.0       Yes  
1                 7.0        No  
2                 4.0       Yes  
3                 1.0        No  
4                 NaN       Yes  
...               ...       ...  
5195              1.0       Yes  
5196              4.0        No  
5197              5.0        No  
5198              9.0        No  
5199             10.0       Yes  

[5200 rows x 8 columns]

In [170]:
clone['Treatment Type'].unique()

array(['Therapy', 'Surgery', nan, 'Medication'], dtype=object)

In [169]:
surgery = clone.query('`Treatment Type` == "Surgery"') 

Age  Gender Smoking Status  Lung Capacity Disease Type Treatment Type  \
1     34.0  Female            Yes            NaN   Bronchitis        Surgery   
4     43.0    Male            Yes           4.60         COPD        Surgery   
7     72.0    Male            NaN           2.61  Lung Cancer        Surgery   
11    21.0    Male             No           1.37    Pneumonia        Surgery   
22    34.0    Male             No           3.20    Pneumonia        Surgery   
25    66.0    Male            NaN           1.17  Lung Cancer        Surgery   
26    81.0  Female            Yes           3.97    Pneumonia        Surgery   
33    40.0    Male            Yes           1.73       Asthma        Surgery   
36    23.0  Female             No           5.77    Pneumonia        Surgery   
37    79.0  Female             No           1.58    Pneumonia        Surgery   
39    28.0  Female             No           4.67    Pneumonia        Surgery   
41    21.0    Male            Yes           4.23          NaN        Surgery   
43    63.0    Male            Yes           1.53    Pneumonia        Surgery   
47    55.0  Female             No           5.16   Bronchitis        Surgery   
48     NaN  Female             No           1.36       Asthma        Surgery   
49    23.0    Male             No           4.45         COPD        Surgery   
52    73.0    Male             No           2.70   Bronchitis        Surgery   
56    37.0  Female            Yes           5.12   Bronchitis        Surgery   
58    53.0     NaN             No           1.51    Pneumonia        Surgery   
59    81.0  Female            Yes           1.31         COPD        Surgery   
60    33.0  Female             No           1.26         COPD        Surgery   
65    72.0     NaN            Yes           1.25  Lung Cancer        Surgery   
66    43.0    Male             No           2.11       Asthma        Surgery   
79    27.0     NaN            Yes           4.69  Lung Cancer        Surgery   
84    60.0     NaN             No           2.72  Lung Cancer        Surgery   
88     NaN  Female             No            NaN         COPD        Surgery   
98    22.0  Female             No           2.23         COPD        Surgery   
101   33.0    Male            Yes           5.91       Asthma        Surgery   
105   61.0  Female            Yes           4.61   Bronchitis        Surgery   
107   82.0    Male             No           3.21       Asthma        Surgery   
120   61.0  Female            Yes           4.32         COPD        Surgery   
125   47.0  Female             No           3.19  Lung Cancer        Surgery   
128   49.0    Male             No           3.51          NaN        Surgery   
129   81.0    Male            Yes           2.61   Bronchitis        Surgery   
142   43.0    Male             No           3.81    Pneumonia        Surgery   
146   81.0  Female             No           5.09  Lung Cancer        Surgery   
148   71.0    Male            NaN           2.28       Asthma        Surgery   
153   75.0  Female            Yes           1.24         COPD        Surgery   
154    NaN    Male             No           2.10    Pneumonia        Surgery   
155   21.0  Female            NaN           4.53    Pneumonia        Surgery   
158   20.0  Female             No           4.49    Pneumonia        Surgery   
167   74.0    Male            Yes           3.54         COPD        Surgery   
168   75.0    Male             No           1.12       Asthma        Surgery   
170   57.0    Male             No           5.10  Lung Cancer        Surgery   
174   30.0    Male             No            NaN         COPD        Surgery   
176   78.0  Female            Yes           5.18          NaN        Surgery   
177   89.0  Female             No           5.84       Asthma        Surgery   
178   22.0  Female             No           3.19   Bronchitis        Surgery   
181   55.0    Male             No           3.13         COPD        Surgery   
183    

In [ ]:
g = clone.groupby('Age').agg[['mean', 'max', 'min']].sort_values()

In [181]:
def strsum(group):
    return ''.join([str(x) for x in group.value])

In [34]:
clone

Age  Gender Smoking Status  Lung Capacity Disease Type Treatment Type  \
0     71.0  Female             No           4.49         COPD        Therapy   
1     34.0  Female            Yes            NaN   Bronchitis        Surgery   
2     80.0    Male            Yes           1.95         COPD            NaN   
3     40.0  Female            Yes            NaN   Bronchitis     Medication   
4     43.0    Male            Yes           4.60         COPD        Surgery   
...    ...     ...            ...            ...          ...            ...   
5195  40.0    Male             No           1.43  Lung Cancer     Medication   
5196  21.0     NaN            Yes           1.50         COPD     Medication   
5197  42.0  Female             No           5.53    Pneumonia        Surgery   
5198  82.0    Male             No           3.68   Bronchitis     Medication   
5199  45.0  Female            Yes           3.79    Pneumonia     Medication   

      Hospital Visits Recovered  
0                14.0       Yes  
1                 7.0        No  
2                 4.0       Yes  
3                 1.0        No  
4                 NaN       Yes  
...               ...       ...  
5195              1.0       Yes  
5196              4.0        No  
5197              5.0        No  
5198              9.0        No  
5199             10.0       Yes  

[5200 rows x 8 columns]

In [35]:
clone.value_counts()

Age   Gender  Smoking Status  Lung Capacity  Disease Type  Treatment Type  Hospital Visits  Recovered
23.0  Female  No              3.79           Lung Cancer   Medication      3.0              No           2
47.0  Male    No              5.26           Asthma        Medication      1.0              No           2
82.0  Female  No              3.18           Bronchitis    Surgery         5.0              Yes          2
                              3.16           Bronchitis    Medication      9.0              No           2
32.0  Male    No              3.48           Lung Cancer   Therapy         6.0              No           2
                                                                                                        ..
43.0  Male    No              4.39           Pneumonia     Therapy         9.0              No           1
                              4.70           Pneumonia     Surgery         11.0             No           1
                              4.86        

In [308]:
# Numpy
import numpy as np
a = np.array([1,2,3])
c = np.array([10,21,33])

b = np.array([ (1.5,2,3), (4, 5, 6) ], dtype=float)

In [306]:
d = np.arange(10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [314]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [332]:
np.empty((2, 3))

array([[121860.  , 124825.  ,  16612.  ],
       [ 17489.  ,   7823.35,   8020.04]])

In [324]:
e = np.full((4,2), 4)
e

array([[4, 4],
       [4, 4],
       [4, 4],
       [4, 4]])

In [342]:
np.vsplit((b,2))

TypeError: vsplit() missing 1 required positional argument: 'indices_or_sections'

In [350]:
a

array([1, 2, 3])

In [351]:
a[a<3] # subsetting

array([1, 2])

In [344]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [348]:
b[1,0]

4.0

In [283]:
pd.

Age  Gender Smoking Status  Lung Capacity Disease Type Treatment Type  \
0     71.0  Female             No           4.49         COPD        Therapy   
1     34.0  Female            Yes            NaN   Bronchitis        Surgery   
2     80.0    Male            Yes           1.95         COPD            NaN   
3     40.0  Female            Yes            NaN   Bronchitis     Medication   
4     43.0    Male            Yes           4.60         COPD        Surgery   
...    ...     ...            ...            ...          ...            ...   
5195  40.0    Male             No           1.43  Lung Cancer     Medication   
5196  21.0     NaN            Yes           1.50         COPD     Medication   
5197  42.0  Female             No           5.53    Pneumonia        Surgery   
5198  82.0    Male             No           3.68   Bronchitis     Medication   
5199  45.0  Female            Yes           3.79    Pneumonia     Medication   

      Hospital Visits Recovered  
0                14.0       Yes  
1                 7.0        No  
2                 4.0       Yes  
3                 1.0        No  
4                 NaN       Yes  
...               ...       ...  
5195              1.0       Yes  
5196              4.0        No  
5197              5.0        No  
5198              9.0        No  
5199             10.0       Yes  

[5200 rows x 8 columns]

In [286]:
g = clone.groupby('Gender').sum()

In [36]:
for i , group in g:
    print(i, group)

NameError: name 'g' is not defined

In [302]:
clone['Recovered_num'] = clone['Recovered'].apply(lambda x: 1 if x =='Yes' else 0)

In [298]:
clone.drop_duplicates(inplace=True)

In [304]:
clone.pivot_table(index='Smoking Status',
                 aggfunc='sum')

Age                                       Disease Type  \
Smoking Status                                                                
No              121860.0  COPDBronchitisLung CancerPneumoniaPneumoniaLun...   
Yes             124825.0  BronchitisCOPDBronchitisCOPDAsthmaPneumoniaBro...   

                                                           Gender  \
Smoking Status                                                      
No              FemaleFemaleFemaleMaleMaleFemaleFemaleMaleFema...   
Yes             FemaleMaleFemaleMaleMaleMaleFemaleMaleMaleFema...   

                Hospital Visits  Lung Capacity  \
Smoking Status                                   
No                      16612.0        7823.35   
Yes                     17489.0        8020.04   

                                                        Recovered  \
Smoking Status                                                      
No              YesYesNoYesYesYesNoNoYesYesYesYesYesNoYesNoYes...   
Yes             NoYesNoYesYesYesYesNoNoYesYesYesNoYesYesNoYesN...   

                Recovered_num  \
Smoking Status                  
No                       1136   
Yes                      1167   

                                                   Treatment Type  
Smoking Status                                                     
No              TherapyMedicationMedicationSurgeryTherapyMedic...  
Yes             SurgeryMedicationSurgeryMedicationMedicationTh...

In [68]:
# scikit-learn
from sklearn import neighbors, datasets, preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [59]:
iris = datasets.load_iris()

In [60]:
X,y = iris.data[:,:2], iris.target

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [70]:
scaler = StandardScaler().fit(X_train)

In [71]:
X_train = scaler.transform(X_train)

In [72]:
X_test = scaler.transform(X_test)

In [75]:
knn = neighbors.KNeighborsClassifier(n_neighbors=5)

In [76]:
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [77]:
y_pred = knn.predict(X_test)

In [78]:
accuracy_score(y_test, y_pred)

0.7105263157894737

In [106]:
import numpy as np
x = np.random.random((5,5))
x

array([[0.98305161, 0.40047122, 0.85551992, 0.95406991, 0.81348577],
       [0.62903071, 0.97688284, 0.70956514, 0.29751182, 0.01678532],
       [0.53780361, 0.51357126, 0.00267378, 0.0869405 , 0.3101717 ],
       [0.65926394, 0.5618719 , 0.89538737, 0.25596091, 0.54626186],
       [0.40025975, 0.33175532, 0.3216097 , 0.80690131, 0.06049682]])

In [96]:
Y = np.array(['A', 'B', 'A', 'C', 'D'])
Y

array(['A', 'B', 'A', 'C', 'D'], dtype='<U1')

In [97]:
# Training and testing data
x_train, x_test, Y_train, Y_test = train_test_split(x, Y, random_state= 0)

In [99]:
# preprocessing the data
scaler = StandardScaler().fit(x_train)
standarized_x = scaler.transform(x_train)
standarized_x_test = scaler.transform(x_test)

In [100]:
# Normalize
from sklearn.preprocessing import Normalizer
scaler = Normalizer().fit(x_train)
normalized_x = scaler.transform(x_train)
normalized_x_test = scaler.transform(x_test)

In [101]:
# Binarization
from sklearn.preprocessing import Binarizer # yes\No
binarizer = Binarizer(threshold = 0.0 ).fit(x)
binarize_x = binarizer.transform(x_test)

In [109]:
# Encoding Category Feature
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
x_train[0] =le.fit_transform(x_train[0])

In [107]:
x_train

array([[0.49938095, 0.33206099, 0.60238702, 0.38600356, 0.33883422],
       [0.64520613, 0.6592486 , 0.44148396, 0.2509046 , 0.21250077],
       [0.06610429, 0.81068394, 0.44594244, 0.83435004, 0.91709053]])